# Generated by Django 5.2.4 on 2025-07-22 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': 'Ocupação',
                'verbose_name_plural': 'Ocupações',
            },
        ),
        migrations.RemoveField(
            model_name='desafioleitura',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='progressoleitura',
            name='progresso_paginas',
        ),
        migrations.RemoveField(
            model_name='rankingleitura',
            name='data_registro',
        ),
        migrations.AlterField(
            model_name='desafioleitura',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='faixa_etaria',
            field=models.CharField(max_length=20, verbose_name='Faixa etária'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='paginas',
            field=models.IntegerField(verbose_name='Número de páginas'),
        ),
        migrations.AlterField(
            model_name='progressoleitura',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='progressoleitura',
            name='estudante',
            field=models.ForeignKey(limit_choices_to={'ocupacao__nome': 'Estudante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudante'),
        ),
        migrations.AlterField(
            model_name='progressoleitura',
            name='status',
            field=models.CharField(choices=[('L', 'Lendo'), ('C', 'Concluído')], max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rankingleitura',
            name='estudante',
            field=models.ForeignKey(limit_choices_to={'ocupacao__nome': 'Estudante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudante'),
        ),
        migrations.AlterField(
            model_name='rankingleitura',
            name='pontos_totais',
            field=models.IntegerField(verbose_name='Pontos totais'),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='recompensas/', verbose_name='Imagem'),
        ),
        migrations.CreateModel(
            name='AvaliacaoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('estudante', models.ForeignKey(limit_choices_to={'ocupacao__nome': 'Estudante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudante')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Avaliação de Leitura',
                'verbose_name_plural': 'Avaliações de Leitura',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True, verbose_name='Data do empréstimo')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de devolução')),
                ('estudante', models.ForeignKey(limit_choices_to={'ocupacao__nome': 'Estudante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudante')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da escola')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.escola', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ocupacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ocupacao', verbose_name='Ocupação'),
        ),
        migrations.CreateModel(
            name='RecomendacaoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=100, verbose_name='Critério de recomendação')),
                ('data_recomendacao', models.DateField(auto_now_add=True, verbose_name='Data da recomendação')),
                ('estudante', models.ForeignKey(limit_choices_to={'ocupacao__nome': 'Estudante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudante')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Recomendação de Leitura',
                'verbose_name_plural': 'Recomendações de Leitura',
            },
        ),
        migrations.CreateModel(
            name='RelatorioDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desempenho', models.TextField(verbose_name='Desempenho')),
                ('recomendacoes', models.TextField(verbose_name='Recomendações')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data do relatório')),
                ('estudante', models.ForeignKey(limit_choices_to={'ocupacao__nome': 'Estudante'}, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL, verbose_name='Estudante')),
                ('professor', models.ForeignKey(limit_choices_to={'ocupacao__nome': 'Professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Relatório de Desempenho',
                'verbose_name_plural': 'Relatórios de Desempenho',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da turma')),
                ('ano_escolar', models.CharField(max_length=10, verbose_name='Ano escolar (6º ao 9º)')),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino')], max_length=1, verbose_name='Turno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.escola', verbose_name='Escola')),
                ('professor_responsavel', models.ForeignKey(limit_choices_to={'ocupacao__nome': 'Professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AddField(
            model_name='desafioleitura',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='rankingleitura',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.turma', verbose_name='Turma'),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
